# configuration file for PDEformer-2-fast
base_config: configs/inference/model-L.yaml
model:
  inr:
    dim_hidden: 256
  load_ckpt: none
  # Set to path/to/model-M.pt or another torch state_dict checkpoint path.
